name: data1030-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - shap
  - matplotlib
  - seaborn
  - textblob
  - jupyterlab
  - ipykernel
  - pip
